const vendemiare_en = {
    name: 'Vendémiaire',
    season: 'Autumn',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Vend%C3%A9miaire_commence_le_22_septembre.jpg',
    days: [
        { date: '22-09', name: 'Grape' },
        { date: '23-09', name: 'Saffron' },
        { date: '24-09', name: 'Chestnut' },
        { date: '25-09', name: 'Autumn Crocus' },
        { date: '26-09', name: 'Horse' },
        { date: '27-09', name: 'Impatiens' },
        { date: '28-09', name: 'Carrot' },
        { date: '29-09', name: 'Amaranth' },
        { date: '30-09', name: 'Parsnip' },
        { date: '01-10', name: 'Vat' },
        { date: '02-10', name: 'Potato' },
        { date: '03-10', name: 'Strawflower' },
        { date: '04-10', name: 'Winter squash' },
        { date: '05-10', name: 'Mignonette' },
        { date: '06-10', name: 'Donkey' },
        { date: '07-10', name: 'Four o\'clock flower' },
        { date: '08-10', name: 'Pumpkin' },
        { date: '09-10', name: 'Buckwheat' },
        { date: '10-10', name: 'Sunflower' },
        { date: '11-10', name: 'Wine-Press' },
        { date: '12-10', name: 'Hemp' },
        { date: '13-10', name: 'Peach' },
        { date: '14-10', name: 'Turnip' },
        { date: '15-10', name: 'Amaryllis' },
        { date: '16-10', name: 'Ox' },
        { date: '17-10', name: 'Eggplant' },
        { date: '18-10', name: 'Chili pepper' },
        { date: '19-10', name: 'Tomato' },
        { date: '20-10', name: 'Barley' },
        { date: '21-10', name: 'Barrel' },
    ]
}

const brumaire_en = {
    name: 'Brumaire',
    season: 'Autumn',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Brumaire_commence_le_23_octobre.jpg',
    days: [
        { date: '22-10', name: 'Apple' },
        { date: '23-10', name: 'Celery' },
        { date: '24-10', name: 'Pear' },
        { date: '25-10', name: 'Beetroot' },
        { date: '26-10', name: 'Goose' },
        { date: '27-10', name: 'Heliotrope' },
        { date: '28-10', name: 'Common fig' },
        { date: '29-10', name: 'Black Salsify' },
        { date: '30-10', name: 'Chequer Tree' },
        { date: '31-10', name: 'Plough' },
        { date: '01-11', name: 'Salsify' },
        { date: '02-11', name: 'Water caltrop' },
        { date: '03-11', name: 'Jerusalem artichoke' },
        { date: '04-11', name: 'Endive' },
        { date: '05-11', name: 'Turkey' },
        { date: '06-11', name: 'Skirret' },
        { date: '07-11', name: 'Watercress' },
        { date: '08-11', name: 'Leadworts' },
        { date: '09-11', name: 'Pomegranate' },
        { date: '10-11', name: 'Harrow' },
        { date: '11-11', name: 'Baccharis' },
        { date: '12-11', name: 'Azarole' },
        { date: '13-11', name: 'Madder' },
        { date: '14-11', name: 'Orange' },
        { date: '15-11', name: 'Pheasant' },
        { date: '16-11', name: 'Pistachio Nut' },
        { date: '17-11', name: 'Tuberous pea' },
        { date: '18-11', name: 'Quince' },
        { date: '19-11', name: 'Service tree' },
        { date: '20-11', name: 'Roller' },
    ],
}

const frimaire_en = {
    name: 'Frimaire',
    season: 'Autumn',
    img: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Frimaire_commence_le_22_novembre.jpg',
    days: [
        { date: '21-11', name: 'Rampion' },
        { date: '22-11', name: 'Cattle turnip' },
        { date: '23-11', name: 'Chicory' },
        { date: '24-11', name: 'Medlar' },
        { date: '25-11', name: 'Pig' },
        { date: '26-11', name: 'Lamb\'s lettuce' },
        { date: '27-11', name: 'Cauliflower' },
        { date: '28-11', name: 'Honey' },
        { date: '29-11', name: 'Juniper' },
        { date: '30-11', name: 'Pickaxe' },
        { date: '01-12', name: 'Wax' },
        { date: '02-12', name: 'Horseradish' },
        { date: '03-12', name: 'Cedar tree' },
        { date: '04-12', name: 'Fir' },
        { date: '05-12', name: 'Roe deer' },
        { date: '06-12', name: 'Gorse' },
        { date: '07-12', name: 'Cypress Tree' },
        { date: '08-12', name: 'Ivy' },
        { date: '09-12', name: 'Savin Juniper' },
        { date: '10-12', name: 'Grub-hoe' },
        { date: '11-12', name: 'Sugar Maple' },
        { date: '12-12', name: 'Heather' },
        { date: '13-12', name: 'Reed plant' },
        { date: '14-12', name: 'Sorrel' },
        { date: '15-12', name: 'Cricket' },
        { date: '16-12', name: 'Pine nut' },
        { date: '17-12', name: 'Cork' },
        { date: '18-12', name: 'Truffle' },
        { date: '19-12', name: 'Olive' },
        { date: '20-12', name: 'Shovel' },
    ],
}

const nivose_en = {
    name: 'Nivôse',
    season: 'Winter',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Niv%C3%B4se_commence_le_22_d%C3%A9cembre.jpg',
    days: [
        { date: '21-12', name: 'Peat' },
        { date: '22-12', name: 'Coal' },
        { date: '23-12', name: 'Bitumen' },
        { date: '24-12', name: 'Sulphur' },
        { date: '25-12', name: 'Dog' },
        { date: '26-12', name: 'Lava' },
        { date: '27-12', name: 'Topsoil' },
        { date: '28-12', name: 'Manure' },
        { date: '29-12', name: 'Saltpeter' },
        { date: '30-12', name: 'Flail' },
        { date: '31-12', name: 'Granite' },
        { date: '01-01', name: 'Clay' },
        { date: '02-01', name: 'Slate' },
        { date: '03-01', name: 'Sandstone' },
        { date: '04-01', name: 'Rabbit' },
        { date: '05-01', name: 'Flint' },
        { date: '06-01', name: 'Marl' },
        { date: '07-01', name: 'Limestone' },
        { date: '08-01', name: 'Marble' },
        { date: '09-01', name: 'Winnowing fan' },
        { date: '10-01', name: 'Gypsum' },
        { date: '11-01', name: 'Salt' },
        { date: '12-01', name: 'Iron' },
        { date: '13-01', name: 'Copper' },
        { date: '14-01', name: 'Cat' },
        { date: '15-01', name: 'Tin' },
        { date: '16-01', name: 'Lead' },
        { date: '17-01', name: 'Zinc' },
        { date: '18-01', name: 'Mercury' },
        { date: '19-01', name: 'Sieve' },
    ],
}

const pluviose_en = {
    name: 'Pluviôse',
    season: 'Winter',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Pluvi%C3%B4se_commence_le_21_ou_22_janvier.jpg',
    days: [
        { date: '20-01', name: 'Spurge-laurel' },
        { date: '21-01', name: 'Moss' },
        { date: '22-01', name: 'Butcher\'s Broom' },
        { date: '23-01', name: 'Snowdrop' },
        { date: '24-01', name: 'Bull' },
        { date: '25-01', name: 'Laurustinus' },
        { date: '26-01', name: 'Tinder polypore' },
        { date: '27-01', name: 'Daphne mezereum' },
        { date: '28-01', name: 'Poplar' },
        { date: '29-01', name: 'Axe' },
        { date: '30-01', name: 'Hellebore' },
        { date: '31-01', name: 'Broccoli' },
        { date: '01-02', name: 'Bay laurel' },
        { date: '02-02', name: 'Filbert' },
        { date: '03-02', name: 'Cow' },
        { date: '04-02', name: 'Box Tree' },
        { date: '05-02', name: 'Lichen' },
        { date: '06-02', name: 'Yew tree' },
        { date: '07-02', name: 'Lungwort' },
        { date: '08-02', name: 'Billhook' },
        { date: '09-02', name: 'Pennycress' },
        { date: '10-02', name: 'Rose Daphne' },
        { date: '11-02', name: 'Couch grass' },
        { date: '12-02', name: 'Common Knotgrass' },
        { date: '13-02', name: 'Hare' },
        { date: '14-02', name: 'Woad' },
        { date: '15-02', name: 'Hazel' },
        { date: '16-02', name: 'Cyclamen' },
        { date: '17-02', name: 'Celandine' },
        { date: '18-02', name: 'Sleigh' },
    ],
}

const ventose_en = {
    name: 'Ventôse',
    season: 'Winter',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Vent%C3%B4se_commence_le_20_ou_21_f%C3%A9vrier.jpg',
    days: [
        { date: '19-02', name: 'Coltsfoot' },
        { date: '20-02', name: 'Dogwood' },
        { date: '21-02', name: 'Matthiola' },
        { date: '22-02', name: 'Privet' },
        { date: '23-02', name: 'Billygoat' },
        { date: '24-02', name: 'Wild Ginger' },
        { date: '25-02', name: 'Italian Buckthorn' },
        { date: '26-02', name: 'Violet' },
        { date: '27-02', name: 'Goat Willow' },
        { date: '28-02', name: 'Spade' },
        { date: '01-03', name: 'Narcissus' },
        { date: '02-03', name: 'Elm' },
        { date: '03-03', name: 'Common fumitory' },
        { date: '04-03', name: 'Hedge mustard' },
        { date: '05-03', name: 'Goat' },
        { date: '06-03', name: 'Spinach' },
        { date: '07-03', name: 'Doronicum' },
        { date: '08-03', name: 'Pimpernel' },
        { date: '09-03', name: 'Chervil' },
        { date: '10-03', name: 'Gardener\'s Line' },
        { date: '11-03', name: 'Mandrake' },
        { date: '12-03', name: 'Parsley' },
        { date: '13-03', name: 'Scurvy-grass' },
        { date: '14-03', name: 'Daisy' },
        { date: '15-03', name: 'Tuna' },
        { date: '16-03', name: 'Dandelion' },
        { date: '17-03', name: 'Wood Anemone' },
        { date: '18-03', name: 'Maidenhair fern' },
        { date: '19-03', name: 'Ash tree' },
        { date: '20-03', name: 'Dibber)' },
    ],
}

const germinal_en = {
    name: 'Germinal',
    season: 'Spring',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Germinal_commence_le_21_ou_22_mars.jpg',
    days: [
        { date: '21-03', name: 'Primrose' },
        { date: '22-03', name: 'Plane Tree' },
        { date: '23-03', name: 'Asparagus' },
        { date: '24-03', name: 'Tulip' },
        { date: '25-03', name: 'Hen' },
        { date: '26-03', name: 'Chard' },
        { date: '27-03', name: 'Birch' },
        { date: '28-03', name: 'Daffodil' },
        { date: '29-03', name: 'Alder' },
        { date: '30-03', name: 'Incubator' },
        { date: '31-03', name: 'Periwinkle' },
        { date: '01-04', name: 'Hornbeam' },
        { date: '02-04', name: 'Morel' },
        { date: '03-04', name: 'Beech Tree' },
        { date: '04-04', name: 'Bee' },
        { date: '05-04', name: 'Lettuce' },
        { date: '06-04', name: 'Larch' },
        { date: '07-04', name: 'Hemlock' },
        { date: '08-04', name: 'Radish' },
        { date: '09-04', name: 'Beehive' },
        { date: '10-04', name: 'Judas tree' },
        { date: '11-04', name: 'Romaine lettuce' },
        { date: '12-04', name: 'Horse chestnut' },
        { date: '13-04', name: 'Arugula or Rocket' },
        { date: '14-04', name: 'Pigeon' },
        { date: '15-04', name: 'Lilac' },
        { date: '16-04', name: 'Anemone' },
        { date: '17-04', name: 'Pansy' },
        { date: '18-04', name: 'Bilberry' },
        { date: '19-04', name: 'Grafting knife' },
    ],
}

const floreal_en = {
    name: 'Floréal',
    season: 'Spring',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flor%C3%A9al_commence_le_21_avril.jpg',
    days: [
        { date: '20-04', name: 'Rose' },
        { date: '21-04', name: 'Oak Tree' },
        { date: '22-04', name: 'Fern' },
        { date: '23-04', name: 'Hawthorn' },
        { date: '24-04', name: 'Nightingale' },
        { date: '25-04', name: 'Common Columbine' },
        { date: '26-04', name: 'Lily of the valley' },
        { date: '27-04', name: 'Button mushroom' },
        { date: '28-04', name: 'Hyacinth' },
        { date: '29-04', name: 'Rake' },
        { date: '30-04', name: 'Rhubarb' },
        { date: '01-05', name: 'Sainfoin' },
        { date: '02-05', name: 'Wallflower' },
        { date: '03-05', name: 'Fan Palm tree' },
        { date: '04-05', name: 'Silkworm' },
        { date: '05-05', name: 'Comfrey' },
        { date: '06-05', name: 'Salad burnet' },
        { date: '07-05', name: 'Basket of Gold' },
        { date: '08-05', name: 'Orache' },
        { date: '09-05', name: 'Weeding hoe' },
        { date: '10-05', name: 'Sea thrift' },
        { date: '11-05', name: 'Fritillary' },
        { date: '12-05', name: 'Borage' },
        { date: '13-05', name: 'Valerian' },
        { date: '14-05', name: 'Carp' },
        { date: '15-05', name: 'Euonymus' },
        { date: '16-05', name: 'Chives' },
        { date: '17-05', name: 'Bugloss' },
        { date: '18-05', name: 'White mustard' },
        { date: '19-05', name: 'Shepherd\'s crook' },
    ],
}

const prairial_en = {
    name: 'Prairial',
    season: 'Spring',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Prairial_commence_le_21_mai.jpg',
    days: [
        { date: '20-05', name: 'Lucerne' },
        { date: '21-05', name: 'Daylily' },
        { date: '22-05', name: 'Clover' },
        { date: '23-05', name: 'Angelica' },
        { date: '24-05', name: 'Duck' },
        { date: '25-05', name: 'Lemon balm' },
        { date: '26-05', name: 'Oat grass' },
        { date: '27-05', name: 'Martagon lily' },
        { date: '28-05', name: 'Wild Thyme' },
        { date: '29-05', name: 'Scythe' },
        { date: '30-05', name: 'Strawberry' },
        { date: '31-05', name: 'Betony' },
        { date: '01-06', name: 'Pea' },
        { date: '02-06', name: 'Acacia' },
        { date: '03-06', name: 'Quail' },
        { date: '04-06', name: 'Carnation' },
        { date: '05-06', name: 'Elderberry' },
        { date: '06-06', name: 'Poppy plant' },
        { date: '07-06', name: 'Linden or Lime tree' },
        { date: '08-06', name: 'Pitchfork' },
        { date: '09-06', name: 'Cornflower' },
        { date: '10-06', name: 'Camomile' },
        { date: '11-06', name: 'Honeysuckle' },
        { date: '12-06', name: 'Bedstraw' },
        { date: '13-06', name: 'Tench' },
        { date: '14-06', name: 'Jasmine' },
        { date: '15-06', name: 'Vervain' },
        { date: '16-06', name: 'Thyme' },
        { date: '17-06', name: 'Peony' },
        { date: '18-06', name: 'Handcart' },
    ],
}

const messidor_en = {
    name: 'Messidor',
    season: 'Summer',
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Messidor_commence_le_21_ou_22_juin.jpg',
    days: [
        { date: '19-06', name: 'Rye' },
        { date: '20-06', name: 'Oat' },
        { date: '21-06', name: 'Onion' },
        { date: '22-06', name: 'Speedwell' },
        { date: '23-06', name: 'Mule' },
        { date: '24-06', name: 'Rosemary' },
        { date: '25-06', name: 'Cucumber' },
        { date: '26-06', name: 'Shallot' },
        { date: '27-06', name: 'Wormwood' },
        { date: '28-06', name: 'Sickle' },
        { date: '29-06', name: 'Coriander' },
        { date: '30-06', name: 'Artichoke' },
        { date: '01-07', name: 'Clove' },
        { date: '02-07', name: 'Lavender' },
        { date: '03-07', name: 'Chamois' },
        { date: '04-07', name: 'Tobacco' },
        { date: '05-07', name: 'Redcurrant' },
        { date: '06-07', name: 'Hairy Vetchling' },
        { date: '07-07', name: 'Cherry' },
        { date: '08-07', name: 'Park' },
        { date: '09-07', name: 'Mint' },
        { date: '10-07', name: 'Cumin' },
        { date: '11-07', name: 'Bean' },
        { date: '12-07', name: 'Alkanet' },
        { date: '13-07', name: 'Guineafowl' },
        { date: '14-07', name: 'Sage' },
        { date: '15-07', name: 'Garlic' },
        { date: '16-07', name: 'Tare' },
        { date: '17-07', name: 'Wheat' },
        { date: '18-07', name: 'Shawm)' },
    ],
}

const thermidor_en = {
    name: 'Thermidor',
    season: 'Summer',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Thermidor_commence_le_20_ou_21_juillet.jpg',
    days: [
        { date: '19-07', name: 'Spelt' },
        { date: '20-07', name: 'Common mullein' },
        { date: '21-07', name: 'Melon' },
        { date: '22-07', name: 'Ryegrass' },
        { date: '23-07', name: 'Ram' },
        { date: '24-07', name: 'Horsetail' },
        { date: '25-07', name: 'Mugwort' },
        { date: '26-07', name: 'Safflower' },
        { date: '27-07', name: 'Blackberry' },
        { date: '28-07', name: 'Watering can' },
        { date: '29-07', name: 'Foxtail millet' },
        { date: '30-07', name: 'Common Glasswort' },
        { date: '31-07', name: 'Apricot' },
        { date: '01-08', name: 'Basil' },
        { date: '02-08', name: 'Ewe' },
        { date: '03-08', name: 'Marshmallow' },
        { date: '04-08', name: 'Flax' },
        { date: '05-08', name: 'Almond' },
        { date: '06-08', name: 'Gentian' },
        { date: '07-08', name: 'Lock' },
        { date: '08-08', name: 'Carline thistle' },
        { date: '09-08', name: 'Caper' },
        { date: '10-08', name: 'Lentil' },
        { date: '11-08', name: 'Inula' },
        { date: '12-08', name: 'Otter' },
        { date: '13-08', name: 'Myrtle' },
        { date: '14-08', name: 'Rapeseed' },
        { date: '15-08', name: 'Lupin' },
        { date: '16-08', name: 'Cotton' },
        { date: '17-08', name: 'Mill' },
    ],
}

const fructidor_en = {
    name: 'Fructidor',
    season: 'Summer',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Fructidor_commence_le_21_ou_22_ao%C3%BBt.jpg',
    days: [
        { date: '18-08', name: 'Plum' },
        { date: '19-08', name: 'Millet' },
        { date: '20-08', name: 'Puffball' },
        { date: '21-08', name: 'Six-row Barley' },
        { date: '22-08', name: 'Salmon' },
        { date: '23-08', name: 'Tuberose' },
        { date: '24-08', name: 'Winter Barley' },
        { date: '25-08', name: 'Apocynum' },
        { date: '26-08', name: 'Liquorice' },
        { date: '27-08', name: 'Ladder' },
        { date: '28-08', name: 'Watermelon' },
        { date: '29-08', name: 'Fennel' },
        { date: '30-08', name: 'European Barberry' },
        { date: '31-08', name: 'Walnut' },
        { date: '01-09', name: 'Trout' },
        { date: '02-09', name: 'Lemon' },
        { date: '03-09', name: 'Teasel' },
        { date: '04-09', name: 'Buckthorn' },
        { date: '05-09', name: 'Mexican Marigold' },
        { date: '06-09', name: 'Harvesting basket' },
        { date: '07-09', name: 'Wild Rose' },
        { date: '08-09', name: 'Hazelnut' },
        { date: '09-09', name: 'Hops' },
        { date: '10-09', name: 'Sorghum' },
        { date: '11-09', name: 'Crayfish' },
        { date: '12-09', name: 'Bitter orange' },
        { date: '13-09', name: 'Goldenrod' },
        { date: '14-09', name: 'Maize or Corn' },
        { date: '15-09', name: 'Sweet Chestnut' },
        { date: '16-09', name: 'Pack Basket' },
    ],
}

const sansculottides_en = {
    name: 'Sansculottides',
    season: 'Interseason',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Calendrier-republicain-debucourt2.jpg/1017px-Calendrier-republicain-debucourt2.jpg',
    days: [
        { date: '17-09', name: 'Celebration of Virtue' },
        { date: '18-09', name: 'Celebration of Talent' },
        { date: '19-09', name: 'Celebration of Labour' },
        { date: '20-09', name: 'Celebration of Convictions' },
        { date: '21-09', name: 'Celebration of Honors (Awards)' },
        // { date: '22-09', name: 'Celebration of Revolution' }, // TODO only leap years, handle it
    ],
}

const months_en = [vendemiare_en, brumaire_en, frimaire_en, nivose_en, pluviose_en, ventose_en, germinal_en, floreal_en, prairial_en, messidor_en, thermidor_en, fructidor_en, sansculottides_en]
const dates_en = {}

const vendemiare_ru = {
    name: 'Вандемьера',
    season: 'Осень',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Vend%C3%A9miaire_commence_le_22_septembre.jpg',
    days: [
        { date: '22-09', name: 'Виноград' },
        { date: '23-09', name: 'Шафран' },
        { date: '24-09', name: 'Каштан' },
        { date: '25-09', name: 'Безвременник' },
        { date: '26-09', name: 'Лошадь' },
        { date: '27-09', name: 'Бальзамин' },
        { date: '28-09', name: 'Морковь' },
        { date: '29-09', name: 'Амарант' },
        { date: '30-09', name: 'Пастернак' },
        { date: '01-10', name: 'Чан' },
        { date: '02-10', name: 'Картофель' },
        { date: '03-10', name: 'Бессмертник' },
        { date: '04-10', name: 'Тыква гигантская' },
        { date: '05-10', name: 'Резеда' },
        { date: '06-10', name: 'Осёл' },
        { date: '07-10', name: 'Мирабилис' },
        { date: '08-10', name: 'Тыква обыкновенная' },
        { date: '09-10', name: 'Гречиха' },
        { date: '10-10', name: 'Подсолнечник' },
        { date: '11-10', name: 'Пресс' },
        { date: '12-10', name: 'Конопля' },
        { date: '13-10', name: 'Персик' },
        { date: '14-10', name: 'Репа' },
        { date: '15-10', name: 'Амарилис' },
        { date: '16-10', name: 'Вол' },
        { date: '17-10', name: 'Баклажан' },
        { date: '18-10', name: 'Красный перец' },
        { date: '19-10', name: 'Томат' },
        { date: '20-10', name: 'Ячмень' },
        { date: '21-10', name: 'Бочка' },
    ]
}

const brumaire_ru = {
    name: 'Брюмера',
    season: 'Осень',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Brumaire_commence_le_23_octobre.jpg',
    days: [
        { date: '22-10', name: 'Яблоко' },
        { date: '23-10', name: 'Сельдерей' },
        { date: '24-10', name: 'Груша' },
        { date: '25-10', name: 'Свёкла' },
        { date: '26-10', name: 'Гусь' },
        { date: '27-10', name: 'Гелиотроп' },
        { date: '28-10', name: 'Инжир' },
        { date: '29-10', name: 'Скорцонера' },
        { date: '30-10', name: 'Рябина обыкновенная' },
        { date: '31-10', name: 'Плуг' },
        { date: '01-11', name: 'Козлобородник' },
        { date: '02-11', name: 'Чилим' },
        { date: '03-11', name: 'Топинамбур' },
        { date: '04-11', name: 'Эндивич' },
        { date: '05-11', name: 'Индюк' },
        { date: '06-11', name: 'Поручейник сахарный' },
        { date: '07-11', name: 'Жеруха обыкновенная' },
        { date: '08-11', name: 'Свинчатка' },
        { date: '09-11', name: 'Гранат' },
        { date: '10-11', name: 'Борона' },
        { date: '11-11', name: 'Бакхарис' },
        { date: '12-11', name: 'Боярышник азароль' },
        { date: '13-11', name: 'Марена' },
        { date: '14-11', name: 'Апельсин' },
        { date: '15-11', name: 'Фазан' },
        { date: '16-11', name: 'Фисташка' },
        { date: '17-11', name: 'Чина клубненосная' },
        { date: '18-11', name: 'Айва' },
        { date: '19-11', name: 'Рябина домашняя' },
        { date: '20-11', name: 'Валик' },
    ],
}

const frimaire_ru = {
    name: 'Фримера',
    season: 'Осень',
    img: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Frimaire_commence_le_22_novembre.jpg',
    days: [
        { date: '21-11', name: 'Рапунцель' },
        { date: '22-11', name: 'Турнепс' },
        { date: '23-11', name: 'Цикорий' },
        { date: '24-11', name: 'Мушмула германская' },
        { date: '25-11', name: 'Свинья' },
        { date: '26-11', name: 'Полевой салат' },
        { date: '27-11', name: 'Цветная капуста' },
        { date: '28-11', name: 'Мёд' },
        { date: '29-11', name: 'Можжевельник' },
        { date: '30-11', name: 'Кирка' },
        { date: '01-12', name: 'Воск' },
        { date: '02-12', name: 'Хрен' },
        { date: '03-12', name: 'Кедр' },
        { date: '04-12', name: 'Ель' },
        { date: '05-12', name: 'Косуля' },
        { date: '06-12', name: 'Утёсник' },
        { date: '07-12', name: 'Кипарис' },
        { date: '08-12', name: 'Плющ' },
        { date: '09-12', name: 'Можжевельник казацкий' },
        { date: '10-12', name: 'Мотыга' },
        { date: '11-12', name: 'Клён сахарный' },
        { date: '12-12', name: 'Вереск' },
        { date: '13-12', name: 'Тростник' },
        { date: '14-12', name: 'Щавель' },
        { date: '15-12', name: 'Сверчок' },
        { date: '16-12', name: 'Кедровый орех' },
        { date: '17-12', name: 'Пробка' },
        { date: '18-12', name: 'Трюфель' },
        { date: '19-12', name: 'Олива' },
        { date: '20-12', name: 'Лопата' },
    ],
}

const nivose_ru = {
    name: 'Нивоза',
    season: 'Зима',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Niv%C3%B4se_commence_le_22_d%C3%A9cembre.jpg',
    days: [
        { date: '21-12', name: 'Торф' },
        { date: '22-12', name: 'Каменный уголь' },
        { date: '23-12', name: 'Битум' },
        { date: '24-12', name: 'Сера' },
        { date: '25-12', name: 'Собака' },
        { date: '26-12', name: 'Лава' },
        { date: '27-12', name: 'Почва' },
        { date: '28-12', name: 'Навоз' },
        { date: '29-12', name: 'Селитра' },
        { date: '30-12', name: 'Цеп' },
        { date: '31-12', name: 'Гранит' },
        { date: '01-01', name: 'Глина' },
        { date: '02-01', name: 'Аспидный сланец' },
        { date: '03-01', name: 'Песчаник' },
        { date: '04-01', name: 'Кролик' },
        { date: '05-01', name: 'Кремень' },
        { date: '06-01', name: 'Мергель' },
        { date: '07-01', name: 'Известняк' },
        { date: '08-01', name: 'Мрамор' },
        { date: '09-01', name: 'Решето для веяния' },
        { date: '10-01', name: 'Гипс' },
        { date: '11-01', name: 'Соль' },
        { date: '12-01', name: 'Железо' },
        { date: '13-01', name: 'Медь' },
        { date: '14-01', name: 'Кошка' },
        { date: '15-01', name: 'Олово' },
        { date: '16-01', name: 'Свинец' },
        { date: '17-01', name: 'Цинк' },
        { date: '18-01', name: 'Ртуть' },
        { date: '19-01', name: 'Сито' },
    ],
}

const pluviose_ru = {
    name: 'Плювиоза',
    season: 'Зима',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Pluvi%C3%B4se_commence_le_21_ou_22_janvier.jpg',
    days: [
        { date: '20-01', name: 'Волчеягодник лавролистный' },
        { date: '21-01', name: 'Мох' },
        { date: '22-01', name: 'Иглица' },
        { date: '23-01', name: 'Подснежник' },
        { date: '24-01', name: 'Бык' },
        { date: '25-01', name: 'Калина лавролистная' },
        { date: '26-01', name: 'Трутовик настоящий' },
        { date: '27-01', name: 'Волчеягодник обыкновенный' },
        { date: '28-01', name: 'Тополь' },
        { date: '29-01', name: 'Топор' },
        { date: '30-01', name: 'Морозник' },
        { date: '31-01', name: 'Брокколи' },
        { date: '01-02', name: 'Лавр' },
        { date: '02-02', name: 'Фундук' },
        { date: '03-02', name: 'Корова' },
        { date: '04-02', name: 'Самшит' },
        { date: '05-02', name: 'Лишайник' },
        { date: '06-02', name: 'Тис' },
        { date: '07-02', name: 'Медуница' },
        { date: '08-02', name: 'Садовый нож' },
        { date: '09-02', name: 'Ярутка / иберис' },
        { date: '10-02', name: 'Волчеягодник' },
        { date: '11-02', name: 'Пырей' },
        { date: '12-02', name: 'Гречишник' },
        { date: '13-02', name: 'Заяц' },
        { date: '14-02', name: 'Вайда' },
        { date: '15-02', name: 'Лещина' },
        { date: '16-02', name: 'Цикламен' },
        { date: '17-02', name: 'Чистотел' },
        { date: '18-02', name: 'Сани' },
    ],
}

const ventose_ru = {
    name: 'Вантоза',
    season: 'Зима',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Vent%C3%B4se_commence_le_20_ou_21_f%C3%A9vrier.jpg',
    days: [
        { date: '19-02', name: 'Мать-и-мачеха' },
        { date: '20-02', name: 'Кизил' },
        { date: '21-02', name: 'Желтушник' },
        { date: '22-02', name: 'Бирючина' },
        { date: '23-02', name: 'Козёл' },
        { date: '24-02', name: 'Копытень' },
        { date: '25-02', name: 'Крушина вечнозелёная' },
        { date: '26-02', name: 'Фиалка' },
        { date: '27-02', name: 'Ива козья' },
        { date: '28-02', name: 'Заступ' },
        { date: '01-03', name: 'Нарцисс' },
        { date: '02-03', name: 'Вяз' },
        { date: '03-03', name: 'Дымянка' },
        { date: '04-03', name: 'Гулявник' },
        { date: '05-03', name: 'Коза' },
        { date: '06-03', name: 'Шпинат' },
        { date: '07-03', name: 'Дороникум' },
        { date: '08-03', name: 'Куриная слепота' },
        { date: '09-03', name: 'Кервель' },
        { date: '10-03', name: 'Шнур / бечёвка' },
        { date: '11-03', name: 'Мандрагора' },
        { date: '12-03', name: 'Петрушка' },
        { date: '13-03', name: 'Ложечница' },
        { date: '14-03', name: 'Маргаритка' },
        { date: '15-03', name: 'Тунец' },
        { date: '16-03', name: 'Одуванчик' },
        { date: '17-03', name: 'Ветреница дубравная' },
        { date: '18-03', name: 'Адиантум венерин волос' },
        { date: '19-03', name: 'Ясень' },
        { date: '20-03', name: 'Сажальный кол' },
    ],
}

const germinal_ru = {
    name: 'Жерминаля',
    season: 'Весна',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Germinal_commence_le_21_ou_22_mars.jpg',
    days: [
        { date: '21-03', name: 'Первоцвет' },
        { date: '22-03', name: 'Платан' },
        { date: '23-03', name: 'Спаржа' },
        { date: '24-03', name: 'Тюльпан' },
        { date: '25-03', name: 'Курица' },
        { date: '26-03', name: 'Мангольд' },
        { date: '27-03', name: 'Берёза' },
        { date: '28-03', name: 'Нарцисс-жонкиль' },
        { date: '29-03', name: 'Ольха' },
        { date: '30-03', name: 'Инкубатор' },
        { date: '31-03', name: 'Барвинок' },
        { date: '01-04', name: 'Граб' },
        { date: '02-04', name: 'Сморчок' },
        { date: '03-04', name: 'Бук' },
        { date: '04-04', name: 'Пчела' },
        { date: '05-04', name: 'Салат' },
        { date: '06-04', name: 'Лиственница' },
        { date: '07-04', name: 'Вёх / болиголов' },
        { date: '08-04', name: 'Редис' },
        { date: '09-04', name: 'Улей' },
        { date: '10-04', name: 'Иудино дерево' },
        { date: '11-04', name: 'Римский салат' },
        { date: '12-04', name: 'Каштан' },
        { date: '13-04', name: 'Сурепка' },
        { date: '14-04', name: 'Голубь' },
        { date: '15-04', name: 'Сирень' },
        { date: '16-04', name: 'Ветреница' },
        { date: '17-04', name: 'Анютины глазки' },
        { date: '18-04', name: 'Черника' },
        { date: '19-04', name: 'Прививочный нож' },
    ],
}

const floreal_ru = {
    name: 'Флореаля',
    season: 'Весна',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flor%C3%A9al_commence_le_21_avril.jpg',
    days: [
        { date: '20-04', name: 'Роза' },
        { date: '21-04', name: 'Дуб' },
        { date: '22-04', name: 'Папоротник' },
        { date: '23-04', name: 'Боярышник' },
        { date: '24-04', name: 'Соловей' },
        { date: '25-04', name: 'Водосбор' },
        { date: '26-04', name: 'Ландыш' },
        { date: '27-04', name: 'Гриб / шампиньон' },
        { date: '28-04', name: 'Гиацинт' },
        { date: '29-04', name: 'Грабли' },
        { date: '30-04', name: 'Ревень' },
        { date: '01-05', name: 'Эспарцет' },
        { date: '02-05', name: 'Желтушник' },
        { date: '03-05', name: 'Хамеропс' },
        { date: '04-05', name: 'Шелковичный червь' },
        { date: '05-05', name: 'Окопник' },
        { date: '06-05', name: 'Кровохлёбка' },
        { date: '07-05', name: 'Алиссум жёлтый' },
        { date: '08-05', name: 'Лебеда' },
        { date: '09-05', name: 'Ручной полольник' },
        { date: '10-05', name: 'Кермек' },
        { date: '11-05', name: 'Рябчик' },
        { date: '12-05', name: 'Огуречник' },
        { date: '13-05', name: 'Валериана' },
        { date: '14-05', name: 'Карп' },
        { date: '15-05', name: 'Бересклет' },
        { date: '16-05', name: 'Лук скорода' },
        { date: '17-05', name: 'Анхуза' },
        { date: '18-05', name: 'Горчица белая' },
        { date: '19-05', name: 'Пастуший посох' },
    ],
}

const prairial_ru = {
    name: 'Прериаля',
    season: 'Весна',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Prairial_commence_le_21_mai.jpg',
    days: [
        { date: '20-05', name: 'Люцерна' },
        { date: '21-05', name: 'Лилейник' },
        { date: '22-05', name: 'Клевер' },
        { date: '23-05', name: 'Дягиль' },
        { date: '24-05', name: 'Утка' },
        { date: '25-05', name: 'Мелисса' },
        { date: '26-05', name: 'Французский райграс' },
        { date: '27-05', name: 'Лилия саранка' },
        { date: '28-05', name: 'Тимьян ползучий / чабрец' },
        { date: '29-05', name: 'Коса' },
        { date: '30-05', name: 'Земляника / клубника' },
        { date: '31-05', name: 'Буквица' },
        { date: '01-06', name: 'Горох' },
        { date: '02-06', name: 'Акация' },
        { date: '03-06', name: 'Перепел' },
        { date: '04-06', name: 'Гвоздика' },
        { date: '05-06', name: 'Бузина' },
        { date: '06-06', name: 'Мак' },
        { date: '07-06', name: 'Липа' },
        { date: '08-06', name: 'Вилы' },
        { date: '09-06', name: 'Василёк' },
        { date: '10-06', name: 'Ромашка' },
        { date: '11-06', name: 'Жимолость' },
        { date: '12-06', name: 'Подмаренник' },
        { date: '13-06', name: 'Линь' },
        { date: '14-06', name: 'Жасмин' },
        { date: '15-06', name: 'Вербена' },
        { date: '16-06', name: 'Тимьян' },
        { date: '17-06', name: 'Пион' },
        { date: '18-06', name: 'Телега' },
    ],
}

const messidor_ru = {
    name: 'Мессидора',
    season: 'Лето',
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Messidor_commence_le_21_ou_22_juin.jpg',
    days: [
        { date: '19-06', name: 'Рожь' },
        { date: '20-06', name: 'Овёс' },
        { date: '21-06', name: 'Лук' },
        { date: '22-06', name: 'Вероника' },
        { date: '23-06', name: 'Мул' },
        { date: '24-06', name: 'Розмарин' },
        { date: '25-06', name: 'Огурец' },
        { date: '26-06', name: 'Лук-шалот' },
        { date: '27-06', name: 'Полынь горькая' },
        { date: '28-06', name: 'Серп' },
        { date: '29-06', name: 'Кориандр' },
        { date: '30-06', name: 'Артишок' },
        { date: '01-07', name: 'Гвоздика' },
        { date: '02-07', name: 'Лаванда' },
        { date: '03-07', name: 'Серна' },
        { date: '04-07', name: 'Табак' },
        { date: '05-07', name: 'Смородина' },
        { date: '06-07', name: 'Чина' },
        { date: '07-07', name: 'Вишня' },
        { date: '08-07', name: 'Загон для скота' },
        { date: '09-07', name: 'Мята' },
        { date: '10-07', name: 'Кумин' },
        { date: '11-07', name: 'Фасоль' },
        { date: '12-07', name: 'Алканна красильная' },
        { date: '13-07', name: 'Цесарка' },
        { date: '14-07', name: 'Шалфей' },
        { date: '15-07', name: 'Чеснок' },
        { date: '16-07', name: 'Горошек' },
        { date: '17-07', name: 'Пшеница' },
        { date: '18-07', name: 'Шалмей' },
    ],
}

const thermidor_ru = {
    name: 'Термидора',
    season: 'Лето',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Thermidor_commence_le_20_ou_21_juillet.jpg',
    days: [
        { date: '19-07', name: 'Полба' },
        { date: '20-07', name: 'Коровяк обыкновенный' },
        { date: '21-07', name: 'Дыня' },
        { date: '22-07', name: 'Плевел' },
        { date: '23-07', name: 'Баран' },
        { date: '24-07', name: 'Хвощ' },
        { date: '25-07', name: 'Полынь' },
        { date: '26-07', name: 'Сафлор' },
        { date: '27-07', name: 'Ежевика' },
        { date: '28-07', name: 'Лейка' },
        { date: '29-07', name: 'Просо' },
        { date: '30-07', name: 'Солерос' },
        { date: '31-07', name: 'Абрикос' },
        { date: '01-08', name: 'Базилик' },
        { date: '02-08', name: 'Овца' },
        { date: '03-08', name: 'Алтей' },
        { date: '04-08', name: 'Лён' },
        { date: '05-08', name: 'Миндаль' },
        { date: '06-08', name: 'Горечавка' },
        { date: '07-08', name: 'Шлюз' },
        { date: '08-08', name: 'Колючник' },
        { date: '09-08', name: 'Каперс' },
        { date: '10-08', name: 'Чечевица' },
        { date: '11-08', name: 'Девясил' },
        { date: '12-08', name: 'Выдра' },
        { date: '13-08', name: 'Мирт' },
        { date: '14-08', name: 'Рапс' },
        { date: '15-08', name: 'Люпин' },
        { date: '16-08', name: 'Хлопок' },
        { date: '17-08', name: 'Мельница' },
    ],
}

const fructidor_ru = {
    name: 'Фрюктидора',
    season: 'Лето',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Fructidor_commence_le_21_ou_22_ao%C3%BBt.jpg',
    days: [
        { date: '18-08', name: 'Слива' },
        { date: '19-08', name: 'Просо' },
        { date: '20-08', name: 'Дождевик' },
        { date: '21-08', name: 'Ячмень шестирядный' },
        { date: '22-08', name: 'Лосось' },
        { date: '23-08', name: 'Тубероза' },
        { date: '24-08', name: 'Озимый ячмень' },
        { date: '25-08', name: 'Кутра' },
        { date: '26-08', name: 'Лакрица' },
        { date: '27-08', name: 'Лестница' },
        { date: '28-08', name: 'Арбуз' },
        { date: '29-08', name: 'Укроп' },
        { date: '30-08', name: 'Inette' },
        { date: '31-08', name: 'Грецкий орех' },
        { date: '01-09', name: 'Форель' },
        { date: '02-09', name: 'Лимон' },
        { date: '03-09', name: 'Ворсянка' },
        { date: '04-09', name: 'Крушина' },
        { date: '05-09', name: 'Бархатцы' },
        { date: '06-09', name: 'Заплечная корзина' },
        { date: '07-09', name: 'Шиповник' },
        { date: '08-09', name: 'Лесной орех' },
        { date: '09-09', name: 'Хмель' },
        { date: '10-09', name: 'Сорго' },
        { date: '11-09', name: 'Рак' },
        { date: '12-09', name: 'Померанец' },
        { date: '13-09', name: 'Золотарник' },
        { date: '14-09', name: 'Кукуруза' },
        { date: '15-09', name: 'Плод каштана' },
        { date: '16-09', name: 'Корзина' },
    ],
}

const sansculottides_ru = {
    name: 'Санкюлотиды',
    season: 'Межсезонье',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Calendrier-republicain-debucourt2.jpg/1017px-Calendrier-republicain-debucourt2.jpg',
    days: [
        { date: '17-09', name: 'День Доблести/Добродетели' },
        { date: '18-09', name: 'День Таланта' },
        { date: '19-09', name: 'День Труда' },
        { date: '20-09', name: 'День Мнений' },
        { date: '21-09', name: 'День Наград' },
        // { date: '22-09', name: 'День Революции' }, // TODO only leap years, handle it
    ],
}

const months_ru = [vendemiare_ru, brumaire_ru, frimaire_ru, nivose_ru, pluviose_ru, ventose_ru, germinal_ru, floreal_ru, prairial_ru, messidor_ru, thermidor_ru, fructidor_ru, sansculottides_ru]
const dates_ru = {}

const vendemiare_fr = {
    name: 'Vendémiaire',
    season: 'Automne',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Vend%C3%A9miaire_commence_le_22_septembre.jpg',
    days: [
        { date: '22-09', name: 'Raisin' },
        { date: '23-09', name: 'Safran' },
        { date: '24-09', name: 'Châtaigne' },
        { date: '25-09', name: 'Colchique' },
        { date: '26-09', name: 'Cheval' },
        { date: '27-09', name: 'Balsamine' },
        { date: '28-09', name: 'Carotte' },
        { date: '29-09', name: 'Amarante' },
        { date: '30-09', name: 'Panais' },
        { date: '01-10', name: 'Cuve' },
        { date: '02-10', name: 'Pomme de terre' },
        { date: '03-10', name: 'Immortelle' },
        { date: '04-10', name: 'Potiron' },
        { date: '05-10', name: 'Réséda' },
        { date: '06-10', name: 'Âne' },
        { date: '07-10', name: 'Belle-de-nuit' },
        { date: '08-10', name: 'Citrouille' },
        { date: '09-10', name: 'Sarrasin' },
        { date: '10-10', name: 'Tournesol' },
        { date: '11-10', name: 'Pressoir' },
        { date: '12-10', name: 'Chanvre' },
        { date: '13-10', name: 'Pêche' },
        { date: '14-10', name: 'Navet' },
        { date: '15-10', name: 'Amaryllis' },
        { date: '16-10', name: 'Bœuf' },
        { date: '17-10', name: 'Aubergine' },
        { date: '18-10', name: 'Piment' },
        { date: '19-10', name: 'Tomate' },
        { date: '20-10', name: 'Orge' },
        { date: '21-10', name: 'Tonneau' },
    ]
}

const brumaire_fr = {
    name: 'Brumaire',
    season: 'Automne',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Brumaire_commence_le_23_octobre.jpg',
    days: [
        { date: '22-10', name: 'Pomme' },
        { date: '23-10', name: 'Céleri' },
        { date: '24-10', name: 'Poire' },
        { date: '25-10', name: 'Betterave' },
        { date: '26-10', name: 'Oie' },
        { date: '27-10', name: 'Héliotrope' },
        { date: '28-10', name: 'Figue' },
        { date: '29-10', name: 'Scorsonère' },
        { date: '30-10', name: 'Alisier' },
        { date: '31-10', name: 'Charrue' },
        { date: '01-11', name: 'Salsifis' },
        { date: '02-11', name: 'Macre' },
        { date: '03-11', name: 'Topinambour' },
        { date: '04-11', name: 'Endive' },
        { date: '05-11', name: 'Dindon' },
        { date: '06-11', name: 'Chervis' },
        { date: '07-11', name: 'Cresson' },
        { date: '08-11', name: 'Dentelaire' },
        { date: '09-11', name: 'Grenade' },
        { date: '10-11', name: 'Herse' },
        { date: '11-11', name: 'Bacchante' },
        { date: '12-11', name: 'Azerole' },
        { date: '13-11', name: 'Garance' },
        { date: '14-11', name: 'Orange' },
        { date: '15-11', name: 'Faisan' },
        { date: '16-11', name: 'Pistache' },
        { date: '17-11', name: 'Macjonc' },
        { date: '18-11', name: 'Coing' },
        { date: '19-11', name: 'Cormier' },
        { date: '20-11', name: 'Rouleau' },
    ],
}

const frimaire_fr = {
    name: 'Frimaire',
    season: 'Automne',
    img: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Frimaire_commence_le_22_novembre.jpg',
    days: [
        { date: '21-11', name: 'Raiponce' },
        { date: '22-11', name: 'Turneps' },
        { date: '23-11', name: 'Chicorée' },
        { date: '24-11', name: 'Nèfle' },
        { date: '25-11', name: 'Cochon' },
        { date: '26-11', name: 'Mâche' },
        { date: '27-11', name: 'Chou-fleur' },
        { date: '28-11', name: 'Miel' },
        { date: '29-11', name: 'Genièvre' },
        { date: '30-11', name: 'Pioche' },
        { date: '01-12', name: 'Cire' },
        { date: '02-12', name: 'Raifort' },
        { date: '03-12', name: 'Cèdre' },
        { date: '04-12', name: 'Sapin' },
        { date: '05-12', name: 'Chevreuil' },
        { date: '06-12', name: 'Ajonc' },
        { date: '07-12', name: 'Cyprès' },
        { date: '08-12', name: 'Lierre' },
        { date: '09-12', name: 'Sabine' },
        { date: '10-12', name: 'Hoyau' },
        { date: '11-12', name: 'Érable sucré' },
        { date: '12-12', name: 'Bruyère' },
        { date: '13-12', name: 'Roseau' },
        { date: '14-12', name: 'Oseille' },
        { date: '15-12', name: 'Grillon' },
        { date: '16-12', name: 'Pignon' },
        { date: '17-12', name: 'Liège' },
        { date: '18-12', name: 'Truffe' },
        { date: '19-12', name: 'Olive' },
        { date: '20-12', name: 'Pelle' },
    ],
}

const nivose_fr = {
    name: 'Nivôse',
    season: 'Hiver',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Niv%C3%B4se_commence_le_22_d%C3%A9cembre.jpg',
    days: [
        { date: '21-12', name: 'Tourbe' },
        { date: '22-12', name: 'Houille' },
        { date: '23-12', name: 'Bitume' },
        { date: '24-12', name: 'Soufre' },
        { date: '25-12', name: 'Chien' },
        { date: '26-12', name: 'Lave' },
        { date: '27-12', name: 'Terre végétale' },
        { date: '28-12', name: 'Fumier' },
        { date: '29-12', name: 'Salpêtre' },
        { date: '30-12', name: 'Fléau' },
        { date: '31-12', name: 'Granit' },
        { date: '01-01', name: 'Argile' },
        { date: '02-01', name: 'Ardoise' },
        { date: '03-01', name: 'Grès' },
        { date: '04-01', name: 'Lapin' },
        { date: '05-01', name: 'Silex' },
        { date: '06-01', name: 'Marne' },
        { date: '07-01', name: 'Pierre à chaux' },
        { date: '08-01', name: 'Marbre' },
        { date: '09-01', name: 'Van' },
        { date: '10-01', name: 'Pierre à plâtre' },
        { date: '11-01', name: 'Sel' },
        { date: '12-01', name: 'Fer' },
        { date: '13-01', name: 'Cuivre' },
        { date: '14-01', name: 'Chat' },
        { date: '15-01', name: 'Étain' },
        { date: '16-01', name: 'Plomb' },
        { date: '17-01', name: 'Zinc' },
        { date: '18-01', name: 'Mercure' },
        { date: '19-01', name: 'Crible' },
    ],
}

const pluviose_fr = {
    name: 'Pluviôse',
    season: 'Hiver',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Pluvi%C3%B4se_commence_le_21_ou_22_janvier.jpg',
    days: [
        { date: '20-01', name: 'Lauréole' },
        { date: '21-01', name: 'Mousse' },
        { date: '22-01', name: 'Fragon' },
        { date: '23-01', name: 'Perce-neige' },
        { date: '24-01', name: 'Taureau' },
        { date: '25-01', name: 'Laurier-tin' },
        { date: '26-01', name: 'Amadouvier' },
        { date: '27-01', name: 'Mézéréon' },
        { date: '28-01', name: 'Peuplier' },
        { date: '29-01', name: 'Cognée' },
        { date: '30-01', name: 'Ellébore' },
        { date: '31-01', name: 'Brocoli' },
        { date: '01-02', name: 'Laurier' },
        { date: '02-02', name: 'Avelinier' },
        { date: '03-02', name: 'Vache' },
        { date: '04-02', name: 'Buis' },
        { date: '05-02', name: 'Lichen' },
        { date: '06-02', name: 'If' },
        { date: '07-02', name: 'Pulmonaire' },
        { date: '08-02', name: 'Serpette' },
        { date: '09-02', name: 'Thlaspi' },
        { date: '10-02', name: 'Thimele' },
        { date: '11-02', name: 'Chiendent' },
        { date: '12-02', name: 'Trainasse' },
        { date: '13-02', name: 'Lièvre' },
        { date: '14-02', name: 'Guède' },
        { date: '15-02', name: 'Noisetier' },
        { date: '16-02', name: 'Cyclamen' },
        { date: '17-02', name: 'Chélidoine' },
        { date: '18-02', name: 'Traîneau' },
    ],
}

const ventose_fr = {
    name: 'Ventôse',
    season: 'Hiver',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Vent%C3%B4se_commence_le_20_ou_21_f%C3%A9vrier.jpg',
    days: [
        { date: '19-02', name: 'Tussilage' },
        { date: '20-02', name: 'Cornouiller' },
        { date: '21-02', name: 'Violier' },
        { date: '22-02', name: 'Troène' },
        { date: '23-02', name: 'Bouc' },
        { date: '24-02', name: 'Asaret' },
        { date: '25-02', name: 'Alaterne' },
        { date: '26-02', name: 'Violette' },
        { date: '27-02', name: 'Marceau' },
        { date: '28-02', name: 'Bêche' },
        { date: '01-03', name: 'Narcisse' },
        { date: '02-03', name: 'Orme' },
        { date: '03-03', name: 'Fumeterre' },
        { date: '04-03', name: 'Vélar' },
        { date: '05-03', name: 'Chèvre' },
        { date: '06-03', name: 'Épinard' },
        { date: '07-03', name: 'Doronic' },
        { date: '08-03', name: 'Mouron' },
        { date: '09-03', name: 'Cerfeuil' },
        { date: '10-03', name: 'Cordeau' },
        { date: '11-03', name: 'Mandragore' },
        { date: '12-03', name: 'Persil' },
        { date: '13-03', name: 'Cochléaria' },
        { date: '14-03', name: 'Pâquerette' },
        { date: '15-03', name: 'Thon' },
        { date: '16-03', name: 'Pissenlit' },
        { date: '17-03', name: 'Sylvie' },
        { date: '18-03', name: 'Capillaire' },
        { date: '19-03', name: 'Frêne' },
        { date: '20-03', name: 'Plantoir' },
    ],
}

const germinal_fr = {
    name: 'Germinal',
    season: 'Printemps',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Germinal_commence_le_21_ou_22_mars.jpg',
    days: [
        { date: '21-03', name: 'Primevère' },
        { date: '22-03', name: 'Platane' },
        { date: '23-03', name: 'Asperge' },
        { date: '24-03', name: 'Tulipe' },
        { date: '25-03', name: 'Poule' },
        { date: '26-03', name: 'Bette' },
        { date: '27-03', name: 'Bouleau' },
        { date: '28-03', name: 'Jonquille' },
        { date: '29-03', name: 'Aulne' },
        { date: '30-03', name: 'Couvoir' },
        { date: '31-03', name: 'Pervenche' },
        { date: '01-04', name: 'Charme' },
        { date: '02-04', name: 'Morille' },
        { date: '03-04', name: 'Hêtre' },
        { date: '04-04', name: 'Abeille' },
        { date: '05-04', name: 'Laitue' },
        { date: '06-04', name: 'Mélèze' },
        { date: '07-04', name: 'Ciguë' },
        { date: '08-04', name: 'Radis' },
        { date: '09-04', name: 'Ruche' },
        { date: '10-04', name: 'Gainier' },
        { date: '11-04', name: 'Romaine' },
        { date: '12-04', name: 'Marronnier' },
        { date: '13-04', name: 'Roquette' },
        { date: '14-04', name: 'Pigeon' },
        { date: '15-04', name: 'Lilas' },
        { date: '16-04', name: 'Anémone' },
        { date: '17-04', name: 'Pensée' },
        { date: '18-04', name: 'Myrtille' },
        { date: '19-04', name: 'Greffoir' },
    ],
}

const floreal_fr = {
    name: 'Floréal',
    season: 'Printemps',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flor%C3%A9al_commence_le_21_avril.jpg',
    days: [
        { date: '20-04', name: 'Rose' },
        { date: '21-04', name: 'Chêne' },
        { date: '22-04', name: 'Fougère' },
        { date: '23-04', name: 'Aubépine' },
        { date: '24-04', name: 'Rossignol' },
        { date: '25-04', name: 'Ancolie' },
        { date: '26-04', name: 'Muguet' },
        { date: '27-04', name: 'Champignon' },
        { date: '28-04', name: 'Hyacinthe' },
        { date: '29-04', name: 'Râteau' },
        { date: '30-04', name: 'Rhubarbe' },
        { date: '01-05', name: 'Sainfoin' },
        { date: '02-05', name: 'Bâton-d\'or' },
        { date: '03-05', name: 'Chamérisier' },
        { date: '04-05', name: 'Ver à soie' },
        { date: '05-05', name: 'Consoude' },
        { date: '06-05', name: 'Pimprenelle' },
        { date: '07-05', name: 'Corbeille d\'or' },
        { date: '08-05', name: 'Arroche' },
        { date: '09-05', name: 'Sarcloir' },
        { date: '10-05', name: 'Statice' },
        { date: '11-05', name: 'Fritillaire' },
        { date: '12-05', name: 'Bourrache' },
        { date: '13-05', name: 'Valériane' },
        { date: '14-05', name: 'Carpe' },
        { date: '15-05', name: 'Fusain' },
        { date: '16-05', name: 'Civette' },
        { date: '17-05', name: 'Buglosse' },
        { date: '18-05', name: 'Sénevé' },
        { date: '19-05', name: 'Houlette' },
    ],
}

const prairial_fr = {
    name: 'Prairial',
    season: 'Printemps',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Prairial_commence_le_21_mai.jpg',
    days: [
        { date: '20-05', name: 'Luzerne' },
        { date: '21-05', name: 'Hémérocalle' },
        { date: '22-05', name: 'Trèfle' },
        { date: '23-05', name: 'Angélique' },
        { date: '24-05', name: 'Canard' },
        { date: '25-05', name: 'Mélisse' },
        { date: '26-05', name: 'Fromental' },
        { date: '27-05', name: 'Martagon' },
        { date: '28-05', name: 'Serpolet' },
        { date: '29-05', name: 'Faux' },
        { date: '30-05', name: 'Fraise' },
        { date: '31-05', name: 'Bétoine' },
        { date: '01-06', name: 'Pois' },
        { date: '02-06', name: 'Acacia' },
        { date: '03-06', name: 'Caille' },
        { date: '04-06', name: 'Œillet' },
        { date: '05-06', name: 'Sureau' },
        { date: '06-06', name: 'Pavot' },
        { date: '07-06', name: 'Tilleul' },
        { date: '08-06', name: 'Fourche' },
        { date: '09-06', name: 'Barbeau' },
        { date: '10-06', name: 'Camomille' },
        { date: '11-06', name: 'Chèvrefeuille' },
        { date: '12-06', name: 'Caille-lait' },
        { date: '13-06', name: 'Tanche' },
        { date: '14-06', name: 'Jasmin' },
        { date: '15-06', name: 'Verveine' },
        { date: '16-06', name: 'Thym' },
        { date: '17-06', name: 'Pivoine' },
        { date: '18-06', name: 'Chariot' },
    ],
}

const messidor_fr = {
    name: 'Messidor',
    season: 'Été',
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Messidor_commence_le_21_ou_22_juin.jpg',
    days: [
        { date: '19-06', name: 'Seigle' },
        { date: '20-06', name: 'Avoine' },
        { date: '21-06', name: 'Oignon' },
        { date: '22-06', name: 'Véronique' },
        { date: '23-06', name: 'Mulet' },
        { date: '24-06', name: 'Romarin' },
        { date: '25-06', name: 'Concombre' },
        { date: '26-06', name: 'Échalote' },
        { date: '27-06', name: 'Absinthe' },
        { date: '28-06', name: 'Faucille' },
        { date: '29-06', name: 'Coriandre' },
        { date: '30-06', name: 'Artichaut' },
        { date: '01-07', name: 'Giroflée' },
        { date: '02-07', name: 'Lavande' },
        { date: '03-07', name: 'Chamois' },
        { date: '04-07', name: 'Tabac' },
        { date: '05-07', name: 'Groseille' },
        { date: '06-07', name: 'Gesse' },
        { date: '07-07', name: 'Cerise' },
        { date: '08-07', name: 'Parc' },
        { date: '09-07', name: 'Menthe' },
        { date: '10-07', name: 'Cumin' },
        { date: '11-07', name: 'Haricot' },
        { date: '12-07', name: 'Orcanète' },
        { date: '13-07', name: 'Pintade' },
        { date: '14-07', name: 'Sauge' },
        { date: '15-07', name: 'Ail' },
        { date: '16-07', name: 'Vesce' },
        { date: '17-07', name: 'Blé' },
        { date: '18-07', name: 'Chalemie' },
    ],
}

const thermidor_fr = {
    name: 'Thermidor',
    season: 'Été',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Thermidor_commence_le_20_ou_21_juillet.jpg',
    days: [
        { date: '19-07', name: 'Épeautre' },
        { date: '20-07', name: 'Bouillon-blanc' },
        { date: '21-07', name: 'Melon' },
        { date: '22-07', name: 'Ivraie' },
        { date: '23-07', name: 'Bélier' },
        { date: '24-07', name: 'Prêle' },
        { date: '25-07', name: 'Armoise' },
        { date: '26-07', name: 'Carthame' },
        { date: '27-07', name: 'Mûre' },
        { date: '28-07', name: 'Arrosoir' },
        { date: '29-07', name: 'Panic' },
        { date: '30-07', name: 'Salicorne' },
        { date: '31-07', name: 'Abricot' },
        { date: '01-08', name: 'Basilic' },
        { date: '02-08', name: 'Brebis' },
        { date: '03-08', name: 'Guimauve' },
        { date: '04-08', name: 'Lin' },
        { date: '05-08', name: 'Amande' },
        { date: '06-08', name: 'Gentiane' },
        { date: '07-08', name: 'Écluse' },
        { date: '08-08', name: 'Carline' },
        { date: '09-08', name: 'Câprier' },
        { date: '10-08', name: 'Lentille' },
        { date: '11-08', name: 'Aunée' },
        { date: '12-08', name: 'Loutre' },
        { date: '13-08', name: 'Myrte' },
        { date: '14-08', name: 'Colza' },
        { date: '15-08', name: 'Lupin' },
        { date: '16-08', name: 'Coton' },
        { date: '17-08', name: 'Moulin' },
    ],
}

const fructidor_fr = {
    name: 'Fructidor',
    season: 'Été',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Fructidor_commence_le_21_ou_22_ao%C3%BBt.jpg',
    days: [
        { date: '18-08', name: 'Prune' },
        { date: '19-08', name: 'Millet' },
        { date: '20-08', name: 'Lycoperdon' },
        { date: '21-08', name: 'Escourgeon' },
        { date: '22-08', name: 'Saumon' },
        { date: '23-08', name: 'Tubéreuse' },
        { date: '24-08', name: 'Sucrion' },
        { date: '25-08', name: 'Apocyn' },
        { date: '26-08', name: 'Réglisse' },
        { date: '27-08', name: 'Échelle' },
        { date: '28-08', name: 'Pastèque' },
        { date: '29-08', name: 'Fenouil' },
        { date: '30-08', name: 'Épine-vinette' },
        { date: '31-08', name: 'Noix' },
        { date: '01-09', name: 'Truite' },
        { date: '02-09', name: 'Citron' },
        { date: '03-09', name: 'Cardère' },
        { date: '04-09', name: 'Nerprun' },
        { date: '05-09', name: 'Tagette' },
        { date: '06-09', name: 'Hotte' },
        { date: '07-09', name: 'Églantier' },
        { date: '08-09', name: 'Noisette' },
        { date: '09-09', name: 'Houblon' },
        { date: '10-09', name: 'Sorgho' },
        { date: '11-09', name: 'Écrevisse' },
        { date: '12-09', name: 'Bigarade' },
        { date: '13-09', name: 'Verge d\'or' },
        { date: '14-09', name: 'Maïs' },
        { date: '15-09', name: 'Marron' },
        { date: '16-09', name: 'Panier' },
    ],
}

const sansculottides_fr = {
    name: 'Sans-culottides',
    season: 'Hors saison',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Calendrier-republicain-debucourt2.jpg/1017px-Calendrier-republicain-debucourt2.jpg',
    days: [
        { date: '17-09', name: 'Jour de la Vertu' },
        { date: '18-09', name: 'Jour du Génie' },
        { date: '19-09', name: 'Jour du Travail' },
        { date: '20-09', name: 'Jour de l\'Opinion' },
        { date: '21-09', name: 'Jour des Récompenses' },
        // { date: '22-09', name: 'Jour de la Révolution' }, // TODO only leap years, handle it
    ],
}

const months_fr = [vendemiare_fr, brumaire_fr, frimaire_fr, nivose_fr, pluviose_fr, ventose_fr, germinal_fr, floreal_fr, prairial_fr, messidor_fr, thermidor_fr, fructidor_fr, sansculottides_fr]
const dates_fr = {}

months_en.forEach(month => {
    month.days.forEach((day, index) => {
        dates_en[day.date] = {
            month,
            dayNumber: index + 1,
            name: day.name,
        }
    })
})

months_ru.forEach(month => {
    month.days.forEach((day, index) => {
        dates_ru[day.date] = {
            month,
            dayNumber: index + 1,
            name: day.name,
        }
    })
})

months_fr.forEach(month => {
    month.days.forEach((day, index) => {
        dates_fr[day.date] = {
            month,
            dayNumber: index + 1,
            name: day.name,
        }
    })
})

function getPreviousDay(date) {
    const previous = new Date(date.getTime())
    previous.setDate(date.getDate() - 1)

    return previous
}

function getNextDay(date) {
    const next = new Date(date.getTime())
    next.setDate(date.getDate() + 1)

    return next
}

function toDateString(date) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
}

window.onload = function () {
    const dateInput = document.querySelector('#date')
    const prevDateBtn = document.querySelector('#prev_date')
    const todayBtn = document.querySelector('#today')
    const nextDateBtn = document.querySelector('#next_date')
    const contentDiv = document.querySelector('#content')

    const todayString = toDateString(new Date)
    dateInput.value = todayString
    const [_, month, date] = todayString.split('-')
    handleDate(date, month)

    function handleDate(date, month) {
        const day_en = dates_en[`${date}-${month}`]
        if (!day_en) {
            alert('no en date found!')
            return
        }

        const day_ru = dates_ru[`${date}-${month}`]
        if (!day_en) {
            alert('no ru date found!')
            return
        }

        const day_fr = dates_fr[`${date}-${month}`]
        if (!day_fr) {
            alert('no fr date found!')
            return
        }

        contentDiv.innerHTML = `<div>
    <h3>Le ${day_fr.dayNumber} ${day_fr.month.name} (${day_fr.name})</h3>
    <h3>${day_en.dayNumber} of ${day_en.month.name} (${day_en.name})</h3>
    <h3>${day_ru.dayNumber} ${day_ru.month.name} (${day_ru.name})</h3>
    <div>
        <p>La saison: ${day_fr.month.season}</p>
        <p>Season: ${day_en.month.season}</p>
        <p>Сезон: ${day_ru.month.season}</p>
        <img src="${day_en.month.img}" alt="month_${day_en.month.name}">
    </div>
</div>`
    }

    dateInput.addEventListener('change', (e) => {
        const [_, month, date] = e.target.value.split('-')
        handleDate(date, month)
    })

    prevDateBtn.addEventListener('click', () => {
        const dateString = toDateString(getPreviousDay(new Date(dateInput.value)))
        dateInput.value = dateString
        const [_, month, date] = dateString.split('-')
        handleDate(date, month)
    })

    todayBtn.addEventListener('click', () => {
        const dateString = toDateString(new Date())
        dateInput.value = dateString
        const [_, month, date] = dateString.split('-')
        handleDate(date, month)
    })

    nextDateBtn.addEventListener('click', () => {
        const dateString = toDateString(getNextDay(new Date(dateInput.value)))
        dateInput.value = dateString
        const [_, month, date] = dateString.split('-')
        handleDate(date, month)
    })
}
